import { z } from "zod";
import { RedmineMembership, RedmineMembershipSchema } from "./membership.schema";
import { RedmineReference, RedmineReferenceSchema } from "./reference.schema";

// Base User Schema
const BaseRedmineUserSchema = z.object({
  id: z.number(),
  login: z.string(),
  admin: z.boolean().optional(),
  firstname: z.string(),
  lastname: z.string(),
  mail: z.string().email().optional(),
  created_on: z.string().datetime(),
  updated_on: z.string().datetime().optional(),
  last_login_on: z.string().datetime().optional().nullable(),
  passwd_changed_on: z.string().datetime().optional(),
  twofa_scheme: z.string().nullable().optional(),
  api_key: z.string().optional(),
  status: z.number().optional(),
  name: z.string().optional(),
});

export type RedmineUser = z.infer<typeof BaseRedmineUserSchema> & {
  memberships?: RedmineMembership[];
  groups?: RedmineReference[];
};

export const RedmineUserSchema: z.ZodType<RedmineUser> = BaseRedmineUserSchema.extend({
  memberships: z.lazy(() => z.array(RedmineMembershipSchema)).optional(),
  groups: z.lazy(() => z.array(RedmineReferenceSchema)).optional(),
});

// API Request Schemas
export const CreateUserRequestSchema = z.object({
  user: z.object({
    login: z.string(),
    firstname: z.string(),
    lastname: z.string(),
    mail: z.string().email(),
    password: z.string().min(8).optional(),
    generate_password: z.boolean().optional(),
  }),
});

export const UpdateUserRequestSchema = z.object({
  user: z.object({
    login: z.string().optional(),
    firstname: z.string().optional(),
    lastname: z.string().optional(),
    mail: z.string().email().optional(),
    password: z.string().min(8).optional(),
  }),
});

export type CreateUserPayload = z.infer<typeof CreateUserRequestSchema>;
export type UpdateUserPayload = z.infer<typeof UpdateUserRequestSchema>;

// Tool Parameter Schemas
export const CreateUserToolSchema = z.object({
  login: z.string().describe("The user's login name."),
  firstname: z.string().describe("The user's first name."),
  lastname: z.string().describe("The user's last name."),
  mail: z
    .string()
    .email("This must be a valid email address.")
    .describe("The user's email address."),
  password: z
    .string()
    .min(8)
    .optional()
    .describe(
      "The user's password. Must be at least 8 characters. Cannot be used with 'generate_password'."
    ),
  generate_password: z
    .boolean()
    .optional()
    .describe(
      "If true, a random password will be generated by Redmine. Cannot be used with 'password'."
    ),
});

export const GetUserToolSchema = z.object({
  id: z.string().describe("The numeric ID of the user to retrieve."),
});

export const ListUsersToolSchema = z.object({});

export const UpdateUserToolSchema = z.object({
  id: z.string().describe("The ID of the user to update."),
  login: z.string().optional().describe("The user's new login name."),
  firstname: z.string().optional().describe("The user's new first name."),
  lastname: z.string().optional().describe("The user's new last name."),
  mail: z.string().email().optional().describe("The user's new email address."),
  password: z
    .string()
    .min(8)
    .optional()
    .describe("The user's new password. Must be at least 8 characters."),
});

export const DeleteUserToolSchema = z.object({
  id: z.string().describe("The ID of the user to delete."),
});

export const GetCurrentUserToolSchema = z.object({
  include: z
    .string()
    .optional()
    .describe("Comma-separated list of related data to include, e.g., 'memberships,groups'."),
});
